name: Syntax Check Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    name: Check for Syntax Errors
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Install OpenJDK 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y


      - name: Verify JDK installation
        run: |
          java -version
          javac -version


      - name: Run Syntax Check
        run: |
          ./mvnw clean verify -DskipTests
